CREATE DATABASE untact;

USE untact;

CREATE TABLE csList (
bno INT PRIMARY KEY AUTO_INCREMENT,
sort VARCHAR(255) NOT NULL,
content VARCHAR(2000) NOT NULL,
writer VARCHAR(50) NOT NULL,
wrdate TIMESTAMP DEFAULT NOW()
);
